export const FETCH_POSTS_SUCCESS= 'FETCH_POSTS_SUCCESS'

export const FETCH_CATEGORY_SUCCESS= 'FETCH_CATEGORY_SUCCESS'

export const FETCH_CATEGORY_OF_A_POST_SUCCESS= 'FETCH_CATEGORY_OF_A_POST_SUCCESS'

export const CREATE_POST_SUCCESS ='CREATE_POST_SUCCESS'

export const FETCH_SINGLE_POSTS_SUCCESS ='FETCH_SINGLE_POSTS_SUCCESS'

export const UPDATE_SINGLE_POSTS_SUCCESS='UPDATE_SINGLE_POSTS_SUCCESS'

export const DELETE_POST_SUCCESS ='DELETE_POST_SUCCESS'

export const FETCH_COMMENT_FOR_SINGLE_POST_SUCCESS='FETCH_COMMENT_FOR_SINGLE_POST_SUCCESS'

export const CREATE_COMMENT_SUCCESS ='CREATE_COMMENT_SUCCESS'

export const FETCH_DETAILS_FOR_SINGLE_POST_SUCCESS ='FETCH_DETAILS_FOR_SINGLE_POST_SUCCESS'

export const UPDATE_DETAILS_FOR_SINGLE_POST_SUCCESS ='UPDATE_DETAILS_FOR_SINGLE_POST_SUCCESS'

export const UPDATE_VOTE_FOR_SINGLE_POST_SUCCESS ='UPDATE_VOTE_FOR_SINGLE_POST_SUCCESS'

export const DELETE_COMMENT_SUCCESS ="DELETE_COMMENT_SUCCESS"

export const FETCH_POST_IN_CATEGORY_SUCCESS = "FETCH_POST_IN_CATEGORY_SUCCESS"

